### ISSUE TITLE
 Toggle condition on multiple components with v-model

### ISSUE THREAD

**Issue by CodingAnton** [phegman/v-show-slide#1]
First of all: great job, thank you for the directive very much ! 

Vue version is '2.5.9'
It would be better to include JSFiddle, but current package has no cdn version. Accordion component works without jQuery - it is simple HTML with 'v-show-slide' directive on each toggle panel. Data is linked to v-model.  'V-show-slide' Boolean conditions are unique for every panel.

Issue: when one input is changed - all panels with directive are triggered.

![issue](https://user-images.githubusercontent.com/30978725/41471970-bc8b2430-70bd-11e8-9a98-b38c4930e43f.gif)

**Comment by phegman** [comment]
Thanks for pointing this out! I just added a check to make sure the value of the directive has changed when the component is updated so this should fix the bug. If you pull in the latest version of the package (1.6) you should be all set!

Let me know if you are still running into issues after pulling in the newest version.

**Comment by CodingAnton** [comment]
All works fine now, thank you!
