### ISSUE TITLE
Callback/events

### ISSUE THREAD

**Issue by mickaelchanrion** [phegman/v-show-slide#3]
Hi,
Thanks for this useful directive!
On my current project, things leads me to a specific need: I have to know when an element ended the collapse/uncollapse animation.

For now, I will just use a combo of setTimeout/clearTimeout because I have no other options but I think it might be interesting to add callbacks or events for:
- open starts
- open ends
- close starts
- close ends

Would it be possible? :)

**Comment by phegman** [comment]
That is an interesting idea, and I could see how it would be useful. I may look into using this approach to add events: https://stackoverflow.com/questions/40655333/vue-js-emit-event-from-directive.

**Comment by mickaelchanrion** [comment]
I didn't this was possible:
`vnode.context.$emit(eventname)`
Yes, I think that this is a good approach

**Comment by phegman** [comment]
Events have been added! https://github.com/phegman/v-show-slide#events
