### ISSUE TITLE
Missing Declaration

### ISSUE THREAD

**Issue by CelticParser** [phegman/v-show-slide#4]
Thnx for the plugin - This works better than Vuetify's `expansion-panels()` (It may be lighter too).

Cli-3 gives the following warning below; If you could add the declaration and/or update the docs, it would be greatly appreciate.

>Could not find a declaration file for module 'v-show-slide'. 'c:/.../node_modules/v-show-slide/dist/v-show-slide.js' implicitly has an 'any' type.
>Try `npm install @types/v-show-slide` if it exists or add a new declaration (.d.ts) file containing `declare module 'v-show-slide';

**Comment by phegman** [comment]
The latest version (v1.7.0) now has TypeScript support
