### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by tommyo** [phegman/v-show-slide#9]
Build not quite right for typescript? Linters not finding `dist/index.d.ts` when using `import VShowSlide from 'v-show-slide'` with error:

```bash
Could not find a declaration file for module 'v-show-slide'. '/path/to/app/node_modules/v-show-slide/dist/v-show-slide.umd.js' implicitly has an 'any' type.
```

However, using `import VShowSlide from 'v-show-slide/src'` works fine.

**Comment by phegman** [comment]
Thanks for the heads up, this should be fixed in the latest version!
